### ISSUE TITLE
Qt 5.4 required?

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap-gui#38]
According to `INSTALL`, tarsnap-gui works on Qt 5.2.1.  However, attempting to compile 1582a7961d395dffffc5beb1b267fca0d84e139a produces:

```
src/taskmanager.cpp: In member function ‘void TaskManager::dequeueTask()’:
src/taskmanager.cpp:801:70: error: no matching function for call to ‘QTimer::singleShot(int, QCoreApplication*, void (*)())’
                 QTimer::singleShot(500, qApp, &QCoreApplication::quit);
                                                                      ^
```

```
$ qmake --version
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu
```

According to http://doc.qt.io/qt-5/qtimer.html#singleShot-2,
```
void QTimer::singleShot(int msec, const QObject * receiver, PointerToMemberFunction method)
```
was introduced in Qt 5.4.

**Comment by shinnok** [comment]
Good find. Fixed.
